### ISSUE TITLE
Text in warning popups should ALWAYS be copy-pastable

### ISSUE THREAD

**Issue by teo1978** [fjenett/javascript-mode-processing#25]
It fills me with rage when a popup appears with a warning or error or a message of any kind, and I can't copy and paste its text. Be it in order to report a bug or google it.

An example is the warning that says that the size cannot be determined from the sketch code, when you pass size() variables as parameters. The text of the message is not copy-pastable.

**Comment by fjenett** [comment]
Not a JS problem as i inherit that dialog box from Processing itself. Please report there.
