### ISSUE TITLE
"console" output is unreadable

### ISSUE THREAD

**Issue by teo1978** [fjenett/javascript-mode-processing#27]
The default style for the pseudo-console, where the output of print and println's is written, shuld by default  be readable, e.g. white text over black background, as it actually used to be some versions ago.
At some point it got broken. Now the text is light grey and the background is slightly-less-light grey, almost the same color. The text is unreadable.

Not sure at this point whether this is more a bug in JS Mode or in PJS itself.
PJS does apply (since 1.4.13) a 'console' class to the console div. So perhaps JS Mode should have a default CSS that results in a decent layout for the console.

**Comment by fjenett** [comment]
Not a JS mode problem but Processing.js, please report there:
https://github.com/processing-js/processing-js/issues

**Comment by teo1978** [comment]
You're right, Sorry.
