### ISSUE TITLE
print and println should html-encode the output

### ISSUE THREAD

**Issue by teo1978** [fjenett/javascript-mode-processing#28]
Test code:
```
println("<test>aaa</test>");
```
Expected visible output in the console:
```
<test>aaa</test>
```
Observed output in the console:
```
aaa
``` 

The same issue can (obviously) be observed by println'ing an XML object.

If you inspect element you'll see that the output is actually there, but since it is interpreted as html by the browser, the tags are not visible.
Print and println should encode the necessary characters into html entities or, perhaps simpler, wrap the output into CDATA blocks (in this case, don't forget to escape any CDATA block that may be present in the string passed to print[ln]), before adding it to the html document.

**Comment by teo1978** [comment]
Actually, this seems to be a regression.
http://matteosistisette.com/upf-redes-x/ejemplos/XML/processing_cajasbolas_xml/
This uses Processing JS 1.4.1 and it works as expected

**Comment by fjenett** [comment]
This has nothing to do with the JavaScript mode, this is a Processing.js issue. Please report there:
https://github.com/processing-js/processing-js/issues

**Comment by teo1978** [comment]
Ouch, I reported to the wrong bug tracker by mistake. I thought I was on the processing-js one, sorry.
