### ISSUE TITLE
touch support throwing an error in chrome

### ISSUE THREAD

**Issue by falquaddoomi** [fjenett/javascript-mode-processing#32]
I'm attempting to run a processing.js sketch on a mobile device, but every time the user initiates a mouse event the following exception is thrown:

    Uncaught ReferenceError: eventHandlers is not defined

The error occurs at the following location in processing.js:
https://github.com/fjenett/javascript-mode-processing/blob/master/resources/template/processing.js#L7575

I would have thought that 'eventHandlers' would be included in the scope where the callback to attachEventHandlers() is being defined, but apparently not. I've been able to replicate this issue using the mobile device emulator in Chrome for Windows v43.0.2357.124 m.

For completeness, I've included a basic sketch that demonstrates the problem:

	void setup() {
	  size(300, 300); 
	}

	PVector m = new PVector(), displace = new PVector();
	boolean pressing = false;
	void mousePressed() {
	  m.set(mouseX, mouseY);
	  pressing = true;
	}

	void mouseReleased() {
	  pressing = false;
	}

	void draw() {
	  background(0);

	  if (pressing) {
		displace = PVector.sub(m, new PVector(mouseX, mouseY));
		float rad = displace.mag()*2.0;
		fill(255);
		ellipse(m.x, m.y, rad, rad);
	  }
	}

**Comment by fjenett** [comment]
Hey, this seems to be not a problem of JavaScript mode but of Processing.js itself. Please check with the latest plain version of [Processing.js](https://github.com/processing-js/processing-js/) and if the problem is still there then report to their issues queue.
