### ISSUE TITLE
not working with pre-release Processing 3.0a11

### ISSUE THREAD

**Issue by liquidzym** [fjenett/javascript-mode-processing#33]
needs rebuild to working with current version which is 3.0a11
cheers

**Comment by GoToLoop** [comment]
Processing's Java mode is in the middle of major restructuring. That's why it's in alpha stage now!
I've got v3.0a5 w/ both JS & CS modes working perfectly!  :D

**Comment by fjenett** [comment]
Ok, thanks for reporting

**Comment by mpbraendle** [comment]
Also not working with 3.0b2. See https://github.com/processing/processing/wiki/Changes-in-3.0 for changes in Modes.

**Comment by fjenett** [comment]
OK, tx

**Comment by dcuartielles** [comment]
also not working for 3b05 when installing from the management tool

**Comment by chrisallick** [comment]
quickly adding not working with 3.0b7 thanks

**Comment by mpbraendle** [comment]
Processing 3 is now out. Would be nice to have JS mode working.

**Comment by fjenett** [comment]
Pinging me won't help … i am very aware of the Processing releases.

With the fundamental changes to the PDE in 3.0 the JS mode is currently too broken to speed-fix. So there are two ways to handle this: wait for me to find more time than just an hour somewhen at night or look into the problem and send me a pull request … :)

**Comment by fjenett** [comment]
Ok, that said i managed to fix most of the problems … if you have a minute please test this version and open new issues for any problems you find:

https://github.com/fjenett/javascript-mode-processing/blob/8204f3ccd7042cac73ee2950b8dfcdc3b4b44bfd/release/JavaScriptMode.zip?raw=true
(download, unzip, move to "modes" folder, restart Processing)

**Comment by GoToLoop** [comment]
It's working for me right now! Just tested this semi cross-mode sketch:  :D

``` js
/** 
 * No Repeat ID Input (v2.0)
 * by GoToLoop (2015/Sep/15)
 *
 * forum.processing.org/two/discussion/12532/
 * windowjs-cross-mode-alert-confirm-prompt-other-js-api-for-java
 *
 * forum.Processing.org/two/discussion/869/check-array-contents-with-arraylist
 *
 * studio.ProcessingTogether.com/sp/pad/export/ro.9$Bjf6i21oXBw
 */

import java.util.List;
final List<String> ids = new ArrayList<String>();
{
  for (String s : window.Array("alert()", "confirm()", "prompt()"))  ids.add(s);
}

void draw() {
  for (String id : ids)  print(id + " ");
  println(" ");

  final String id = window.prompt("Please enter new ID");

  if (id == null)  exit();
  else if (id.length() == 0)  window.alert("Empty ID Input!!!");
  else if (ids.contains(id))  window.alert("ID \"" + id + "\" exists already!!!");
  else {
    window.alert("ID \"" + id + "\" successfully added!!!");
    ids.add(id);
  }
}
```

**Comment by fjenett** [comment]
Great! I will leave it for a couple of days and then clean up and make a release.

**Comment by GoToLoop** [comment]
Now you just need to do the same for CoffeeScript Mode. Even though not that famous.  @_@

**Comment by fjenett** [comment]
It sits on top of JS mode, so once this baby is out the door the other one should be a quick fix.

**Comment by mpbraendle** [comment]
It's working great! Just tried a longer sketch. 
Thank you very much!

**Comment by liquidzym** [comment]
strange,not working in my case,after unzip it and move it to the modes folder.still can't find JavaScriptMode

**Comment by GoToLoop** [comment]
Gotta be subfolder "modes/" from our "sketchBook". It's not the 1 from where Processing is installed in.
Check the real "sketchBook" location by hitting CTRL + `,` (comma).

**Comment by fjenett** [comment]
... and there is a new sketchbook location for Processing 3.

**Comment by liquidzym** [comment]
ah,sorry about that,totally forget about this

**Comment by fjenett** [comment]
Ok, no major bug reports so far. Closing this.

Please open a new issue when you find anything.
